### ISSUE TITLE
[Bug] Handymen leave staffroom without full rest

### ISSUE THREAD

**Issue by ARGAMX** [CorsixTH/CorsixTH#2642]
### Describe the issue

On manual grab and put to staffroom Handymen leave room without full rest.

<img width="222" alt="Screenshot 2024-09-27 at 22 29 49" src="https://github.com/user-attachments/assets/e4bd351f-7ac8-404a-a334-dd836f5c660d">

### Steps to Reproduce

1. *Load save game attached to this ticket*
2. There 2 Handymen in staffroom.
3. First on the sofa, second is already standup and leaving.
4. They leaving staffroom without full rest.
5. After they leave the staffroom put them back in staffroom.
6. Observe that they will leave the staffroom without full rest.

### Expected Behaviour

Handyman should rest to the full in staffroom before leave as in original game.

### Save Game

[handymen_leave_staffroom_before_full_rest.sav.zip](https://github.com/user-attachments/files/17168883/handymen_leave_staffroom_before_full_rest.sav.zip)

### CorsixTH Version

0.68.0 Beta 1

### Operating System

MacOS Sonoma 14.5

**Comment by lewri** [comment]
Naughty, they're answering handyman calls while in the staff room.

```yaml
On call:
plant-watering@50,52
Busy:   busy
Last room:      pharmacy@51,71
Cleaning: 0.333 Watering: 0.333 Repairing: 0.333
-----------------------------------
Clicked on:
<LocalisedString> Current value:humanoid (P. BURCLIFFE) - class: Handyman
Warmth: 0.364   Happiness: 1.000   Fatigue: 0.238  Thirst: 0.000  Toilet_Need: 0.000   Health: 1.000   Service Quality: 0.931
Actions: [walk - going to 50:59   must_happen, walk - going to 49:52, use_object - plant, call_checkpoint, answer_call]
-----------------------------------
-----------------------------------
On call: no
Busy:   busy
Last room:      gp@55,75
Cleaning: 0.333 Watering: 0.333 Repairing: 0.333
-----------------------------------
Clicked on:
<LocalisedString> Current value:humanoid (E. BANLIN) - class: Handyman
Warmth: 0.366   Happiness: 1.000   Fatigue: 0.275  Thirst: 0.000  Toilet_Need: 0.000   Health: 0.860   Service Quality: 0.927
Actions: [use_object - sofa   must_happen, answer_call]
```
