### ISSUE TITLE
[Bug] 'Normal' game speed looks choppy

### ISSUE THREAD

**Issue by masterofobzene** [CorsixTH/CorsixTH#2679]
### Describe the issue

'Normal' game speed looks choppy and 'Maximum speed' looks like actual 'Normal' speed.

Windows 10 x64. 
GoG game files.
Nvidia 3080 gpu
AMD x5900 cpu
16 gb ram.

### Steps to Reproduce

1.  Compare between those speeds.

https://github.com/user-attachments/assets/9347d5a7-eb6a-47b7-99df-d8ad31f7570a

### Expected Behaviour

Normal speed should at least look like "maximum speed" and I suppose "maximum speed" should be faster.

### Have you enabled any current CorsixTH Experimental Features?

- [ ] Right mouse panning
- [ ] Falling actions

### Save Game

Save game attached to report: Yes/No

### CorsixTH Version

0.68

### Operating System

Windows 10 x64

### Theme Hospital Version

GOG.com

### Gamelog.txt

```yaml
Gamelog generated on 2023-11-11 00:59:47
Compiled with api_version: 2684, arch: x64, audio: true, os: windows
SDL renderer: direct3d
Lua 5.4 run with api version: 2684, game version: v0.67, savegame version: 180
```

### Additional Information

This is all it has inside the gamelog.txt, and seems old due to the date it has.
No tampering done and it's the only gamelog.txt that exists.
