### ISSUE TITLE
[Bug] when patient waits for new diag room(s) to be built, after building new diag room, the patient will not move to the new diag room

### ISSUE THREAD

**Issue by vlado2222** [CorsixTH/CorsixTH#2697]
### Describe the issue

Patient exhausted all available diag rooms and doctors were still not sure about the disease. Game asked me what should I do. I selected to let the patient wait for new diag rooms to be built. After building all remaining diag rooms (all were researched) the patient didn't move to any of the new diag rooms. He just waited as if i didn't built any new diag room.

### Steps to Reproduce

1. Load save game attached to this ticket. You will have to reload it couple times until you hit the right chance that doctor is not certain.
[diag required.zip](https://github.com/user-attachments/files/17502183/diag.required.zip)

2. build all remaining diag rooms (ward and cardio)

3. patient will be still waiting for new diag to be built despite they have been built.

### Expected Behaviour

When building new diag room the game should check if there are any patients waiting for new diag to be built and if yes then send them to the newly built diag.

### Have you enabled any current CorsixTH Experimental Features?

- [ ] Right mouse panning
- [ ] Falling actions

### Save Game

Save game attached to report: Yes

### CorsixTH Version

0.68

### Operating System

windows 10

### Theme Hospital Version

Origin

### Gamelog.txt

```yaml
Gamelog generated on 2024-10-22 06:08:44
Compiled with api_version: 2687, arch: x64, audio: true, os: windows, update_check: true
SDL renderer: direct3d
Lua 5.4 run with api version: 2687, game version: v0.68.0, savegame version: 194
```
