### ISSUE TITLE
Doctor frozen in place in Inflation Clinic

### ISSUE THREAD

**Issue by XJDHDR** [CorsixTH/CorsixTH#2723]
### Describe the issue

I was playing through the 3rd level of the campaign (Largechester). At some point, the doctor in the Inflation Clinic just froze in place and became unresponsive. I can't pick him up and he doesn't start moving after being sacked. I also can't edit the room because he won't leave it. Sacking him does cause another doctor to man the room, but just wanders around it (presumably the original doctor is still attached to the machine). 

<img width="311" alt="Image" src="https://github.com/user-attachments/assets/a28763a5-4c26-4e26-8aa6-34e9195d3c4c" />

### Steps to Reproduce

1. Load the save game attached to this ticket.

2. Observe Doctor **G. Benmore** in the Inflation Clinic.

### Expected Behaviour

I expected the doctor to not become frozen in place and unresponsive.

### Have you enabled any current CorsixTH Experimental Features?

- [ ] Right mouse panning
- [ ] Falling actions

### Save Game

Save game attached to report: Yes
[Level 3 - Hard.zip](https://github.com/user-attachments/files/17804892/Level.3.-.Hard.zip)

### CorsixTH Version

0.68

### Operating System

Windows 10

### Theme Hospital Version

GOG.com

### Gamelog.txt

```yaml
Gamelog generated on 2024-11-19 07:45:57
Compiled with api_version: 2687, arch: x64, audio: true, os: windows, update_check: true
SDL renderer: direct3d
Lua 5.4 run with api version: 2687, game version: v0.68.0, savegame version: 194
```
