### ISSUE TITLE
[Bug] Can't load save game. `persistance.lua`: sync fail.

### ISSUE THREAD

**Issue by Poundex** [CorsixTH/CorsixTH#2867]
### Describe the issue

I can't load the game from any of the save files. 
If I try to load my main save file then I get the error
`<LocalisedString> Current value:Error while loading game: /usr/share/corsix-th/Lua/persistance.lua:287: sync fail after 4788 objects (123757 bytes)`

If I try to load from the autosaves I get
`<LocalisedString> Current value:Error while loading game: /usr/share/corsix-th/Lua/persistance.lua:287: Cycle while depersisting permanent object key or userdata metatable after 6920 objects (386789 bytes)`

### Steps to Reproduce

1. *Load save game attached to this ticket*

2. Receive error message

### Expected Behaviour

Loads game?

### Have you enabled any current CorsixTH Experimental Features?

- [ ] Right mouse panning
- [ ] Falling actions

### Save Game

Save game attached to report: Yes

[saves.zip](https://github.com/user-attachments/files/20266137/saves.zip)

### CorsixTH Version

0.68.0

### Operating System

Linux

### Theme Hospital Version

GOG.com

### Gamelog.txt

```yaml
File: gamelog.txt
Gamelog generated on 2025-05-16 20:55:31
Compiled with api_version: 2687, arch: x86_64, audio: true, os: unix, update_check: true
SDL renderer: opengl
Lua 5.4 run with api version: 2687, game version: v0.68.0, savegame version: 194
```
