### ISSUE TITLE
[Bug] Linux: 1920x1080 resolution is not correct

### ISSUE THREAD

**Issue by legluondunet** [CorsixTH/CorsixTH#2884]
### Describe the issue

Hello,

my screen is 1920x1080.
Corsix-TH latest Github code set an incorrect resolution and the videos/game are not fullscreen.
I cannot reproduce this issue with CorsixTH stable (tested Flatpak and AppImage).

### Steps to Reproduce

1. set your desktop resolution to 1920x1080

2. launch Corsix-TH latest Github code and set in options resolution to 1920x1080

### Expected Behaviour

the game should occupy fullscreen

### Have you enabled any current CorsixTH Experimental Features?

- [ ] Right mouse panning
- [ ] Falling actions

### Save Game

Save game attached to report: Not necessary

### CorsixTH Version

7b3107a

### Operating System

Linux Manjaro

### Theme Hospital Version

GOG.com

### Gamelog.txt

```yaml
Gamelog generated on 2025-05-31 00:09:24
Compiled with api_version: 2687, arch: x86_64, audio: true, os: unix, update_check: true
SDL renderer: opengl
Lua 5.4 run with api version: 2687, game version: v0.68.0, savegame version: 194
```

### Additional Information

![Image](https://github.com/user-attachments/assets/0dd82741-68aa-4ebc-af09-080c38de859a)

![Image](https://github.com/user-attachments/assets/2a66d378-9a3f-41df-b2fe-83f0d5e6bd1d)
